import type { JobSource, NormalizedJobInput } from "../types";

export type SearchSpec = {
  source: Extract<JobSource, "indeed" | "dice">;
  query: string;
  location?: string;
};

function enc(value: string) {
  return encodeURIComponent(value.trim());
}

const sourceBuilders: Record<string, (query: string, location?: string) => string> = {
  indeed: (query, location) =>
    `https://www.indeed.com/jobs?q=${enc(query)}${location ? `&l=${enc(location)}` : ""}`,
  dice: (query, location) =>
    `https://www.dice.com/jobs?q=${enc(query)}${location ? `&location=${enc(location)}` : ""}`,
};

export function buildSearchLinkJobs(specs: SearchSpec[], maxResults: number): NormalizedJobInput[] {
  const rows: NormalizedJobInput[] = [];
  const seen = new Set<string>();
  for (const spec of specs) {
    const builder = sourceBuilders[spec.source];
    const sourceUrl = builder(spec.query, spec.location);
    if (seen.has(sourceUrl)) continue;
    seen.add(sourceUrl);
    rows.push({
      title: `${spec.query} jobs${spec.location ? ` — ${spec.location}` : ""}`,
      company: `${spec.source} search`,
      location: spec.location ?? null,
      source: spec.source,
      sourceUrl,
      description:
        `Search link generated by Phase 2 worker for query "${spec.query}"${spec.location ? ` in "${spec.location}"` : ""}. ` +
        "Open this link, review results manually, and import promising job URLs. This avoids heavy scraping and account automation.",
      status: "new",
      priority: "normal",
      visaSignal: "unknown",
      techStack: keywordsFromQuery(spec.query),
      notes: "Phase 2 lightweight search-link record. No job-board credentials or browser automation used.",
    });
    if (rows.length >= maxResults) break;
  }
  return rows;
}

function keywordsFromQuery(query: string) {
  const normalized = query.toLowerCase();
  const stack: string[] = [];
  if (normalized.includes(".net") || normalized.includes("dotnet")) stack.push(".NET");
  if (normalized.includes("c#") || normalized.includes("csharp")) stack.push("C#");
  if (normalized.includes("sql")) stack.push("SQL");
  if (normalized.includes("oracle")) stack.push("Oracle");
  if (normalized.includes("azure")) stack.push("Azure");
  if (normalized.includes("react")) stack.push("React");
  if (normalized.includes("angular")) stack.push("Angular");
  return stack;
}
